### PR TITLE
Ansers added

### PR DESCRIPTION
**Pull request by raisa-khatun**

### CODE REVIEW

**Comment by dlahtine** [comment]
You need to resolve these conflicts before you can merge them into master, you should be able to fix that up by merging master into answer beforehand, then adding, committing, pushing and making another pull request.

Also, your answer to question 1 says that files that are part of the configuration should be ignored: this is not necessarily true, .gradle, .xml, and other configuration files which are not code should be tracked by git.

**Comment by dlahtine** [comment]
oh, but look at answer.txt before you add, and edit it until it's what you want it to be

**Comment by raisa-khatun** [comment]
Thanks David. I resolved the conflict , updated the answer and created
another pull request. What do I have to do now?

And also how do I review your pull request? I often get confused with git.
I appreciate your help.

Thanks

**Comment by raisa-khatun** [comment]
I have seen your answers.  all of them looks good. You can merge now.


Thanks

**Pull request closed without merging**
